title: Tre Quaid
description: >- 
  My personal terminal-themed homepage.
baseurl: "" # leave this empty for GitHub Pages user site
url: "https://tre-quaid.github.io"
theme: jekyll-shell-theme

plugins:
  - jekyll-feed
