title: Tre Quaid
description: My personal terminal-themed homepage.
baseurl: "" # keep this empty for user site
url: "https://tre-quaid.github.io"

theme: null
markdown: kramdown

include:
  - assets/css

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

collections:
  posts:
    output: true
